### PR TITLE
Add missing `babel-loader` dev dependency for Storybook

### PR DESCRIPTION
**Pull request by CloudPower97**
# Description

While adding `knobs` for #794 , `Storybook` greeted me with this nice error: 

`ERR! Error: Cannot find module 'babel-loader/package.json' from '/home/claudio/Documents/React/react-materialize'
ERR!     at module.exports (/home/claudio/Documents/React/react-materialize/node_modules/resolve/lib/sync.js:58:15)
ERR!     at isBabelLoader8 (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-
config.js:68:52)
ERR!     at _default (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config
.js:88:10)
ERR!     at Object.babel (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/common/common-preset.js:19
:45)
ERR!     at accumulationPromise.then.newConfig (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/pres
ets.js:74:72)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:86:5)
ERR!  { Error: Cannot find module 'babel-loader/package.json' from '/home/claudio/Documents/React/react-materialize'
ERR!     at module.exports (/home/claudio/Documents/React/react-materialize/node_modules/resolve/lib/sync.js:58:15)
ERR!     at isBabelLoader8 (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:68:52)
ERR!     at _default (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:88:10)
ERR!     at Object.babel (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/common/common-preset.js:19:45)
ERR!     at accumulationPromise.then.newConfig (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/presets.js:74:72)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:86:5)
ERR!   stack:
ERR!    "Error: Cannot find module 'babel-loader/package.json' from '/home/claudio/Documents/React/react-materialize'\n    at module.exports (/home/claudio/Documents/React/react-materialize/node_modules/resolve/lib/sync.js:58:15)\n    at isBabelLoader8 (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:68:52)\n    at _default (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:88:10)\n    at Object.babel (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/common/common-preset.js:19:45)\n    at accumulationPromise.then.newConfig (/home/claudio/Documents/React/react-materialize/node_modules/@storybook/core/dist/server/presets.js:74:72)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
ERR!   code: 'MODULE_NOT_FOUND' }`

It seems we are missing `babel-loader`.

This P.R fixes this.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by alextrastero** [comment]
How come you didn't need to update `package-lock`, what version of node/npm are u using?

**Comment by CloudPower97** [comment]
> How come you didn't need to update `package-lock`, what version of node/npm are u using?

I'm using `node` v11.13.0, `npm` v6.9.0 and `yarn` v1.15.2.

I think that `yarn` might be the problem here, I didn't push `yarn.lock` because I wasn't sure about that. 

If you wish I can `npm install babel-loader -d` and push `package-lock.json`

Sorry for the inconvenience :smile:

**Comment by alextrastero** [comment]
The thing is that this doesn't fail for me, do you want to try it with npm?

**Comment by CloudPower97** [comment]
> The thing is that this doesn't fail for me, do you want to try it with npm?

Sure, going to try it ASAP.

**Comment by CloudPower97** [comment]
Hey @alextrastero, it seems I have the same exact problem with `npm`. So, `yarn` cannot be the problem here. :confused:

**Comment by alextrastero** [comment]
Still can't reproduce

**Comment by alextrastero** [comment]
Thanks @CloudPower97

**Pull request merged**
