### PR TITLE
Fix broken start of Modal on Next JS

### PR DESCRIPTION
**Pull request by sunaryohadi**
# Description

This will avoid breaking while loading on SSR (NextJS). 

## Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ x ] My changes generate no new warnings
- [ x  ] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by randytarampi** [comment]
Just in case someone's looking for a packaged version, I've published this for my own use in the meantime: https://www.npmjs.com/package/@randy.tarampi/react-materialize.

Fixes a the original issue, https://github.com/react-materialize/react-materialize/issues/1085, and something a bit older too, https://github.com/react-materialize/react-materialize/issues/880.

**Comment by alextrastero** [comment]
Thanks for the proposal, but if no body is null the output is:
`Cannot read property 'appendChild' of null`

**Comment by alextrastero** [comment]
This should be fixed via in `3.8.6`, thanks again for reporting this and submitting a fix!

**Comment by GnarusGBaby** [comment]
I am using version 3.9.6 and still having the issue.

**Pull request closed without merging**
