### PR TITLE
unknown props problem fixed: refer #322

### PR DESCRIPTION
**Pull request by jawadsh123**
This PR fixes the unknown props error pointed in #322

### CODE REVIEW

**Comment by alextrastero** [comment]
@jawadsh123 Hey, thanks for the contribution, would you mind removing the lock files?

**Comment by jawadsh123** [comment]
Pardon me :)
Should have checked the diff before comitting.
Its cleaned up now.

**Comment by alextrastero** [comment]
Thanks @jawadsh123

**Comment by jawadsh123** [comment]
ignore this and please refer #390

**Pull request closed without merging**
