### PR TITLE
Textarea now correctly handles layout classes

### PR DESCRIPTION
**Pull request by CloudPower97**
# Description

Hi there, it's been a while since my last PR. :smile: 
This is just a fix for the `Textarea` component which, at the moment, doesn't correctly handles layout classes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I've written two new test and updated the snapshots.

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by alextrastero** [comment]
Hey @CloudPower97, i'm changing your base to master since we already went live with `3.0.0` :)

**Comment by CloudPower97** [comment]
> Nice, what would you say about adding `knobs` to the `Textarea` story?

Sure, just done.

Please, take a look at #804 as well :smiley:

**Comment by CloudPower97** [comment]
> Just to be picky, let's add some of those newly added layout classes :)

Can you give me an example? Would you like me to add them as `knobs`?

**Comment by alextrastero** [comment]
you could add `<component s={knobs} m={knobs} ...` to try these in storybook

**Comment by CloudPower97** [comment]
@alextrastero Here we go :+1:

**Pull request merged**
