### PR TITLE
Docs serverless

### PR DESCRIPTION
**Pull request by alextrastero**
This is a complete rewrite of the docs, the docs were getting to an unmaintainable state, hopefully now contributors will be more motivated to help out, forgive the mess of commits, it should make sense, there's a TODO list that i'll add to the issues page under `help-wanted`. Please have a look and let me know your concerns :)

### CODE REVIEW

**Comment by isaiah** [comment]
@alextrastero Glad you finally decide to refactor this whole mess. I have a question, seems the pages are still implemented in react, how can we deploy to github pages?

**Comment by alextrastero** [comment]
@isaiah there's no serverside rendering so no need for a server

**Comment by alextrastero** [comment]
I'm not sure if I follow, index.html + main.js = static page

**Comment by alextrastero** [comment]
check it out here: http://alextrastero.github.io/react-materialize

**Comment by Ardhimas** [comment]
Wonderful work you are doing here. If you're still working on this in a month I'll be happy to help out - unfortunately(or fortunately) I'm about to go on vacation so I won't be able to contribute until end of June.

**Comment by alextrastero** [comment]
@isaiah any chance of a review on this? :)

**Comment by isaiah** [comment]
@alextrastero It looks great, a few small things only:
* there are a few broken images, e.g. the logo on the sidenav and avatar on chips page, could be a few more.
* the router should be triggered by hash, so it doesn't redirect to home page on refresh.

**Comment by isaiah** [comment]
Moving the `examples/` folder into `docs/` folder will make it harder for new comer to find them, how about keep it under the root path?

**Comment by alextrastero** [comment]
Yeah, the reason I moved it was because the examples are only used by the docs. Do you think they are used by someone as documentation?

**Comment by isaiah** [comment]
Yes, or else we don't need the complication and just merge them into the
doc files.

Alexander Odell <notifications@github.com> schrieb am Di., 23. Mai 2017,
09:03:

**Comment by alextrastero** [comment]
@isaiah 
- Fixed broken images
- Moved examples outside of docs
- Fixed paths not handles on page reload

Give it a last look and we'll merge this beast :)

**Comment by alextrastero** [comment]
merging this beast !! wish me luck!!

**Pull request merged**
