### PR TITLE
fix props.placement

### PR DESCRIPTION
**Pull request by davidsunsbk**

### CODE REVIEW

**Comment by davidsunsbk** [comment]
Yes, the props should be placement instead of alignment. I've changed rest of the related "alignment" variable name to "placement" in <Slide.js> and fixed the prop validation. Now it should be working and the tests won't have any problem.

**Comment by alextrastero** [comment]
Why not change L30 to `delete props.alignment;` ?

**Comment by davidsunsbk** [comment]
Yeah, I was curious why it's there the first time I looked at the code. I thought maybe it's there for something else, so I avoided modifying that part. If you think deletion won't cause any potential problems, I can make another push.

**Comment by alextrastero** [comment]
Actually what you did is good, I would just remove the `delete props.placement;` and you're done

**Comment by davidsunsbk** [comment]
Sure, thanks!

**Comment by alextrastero** [comment]
thanks again @davidsunsbk, if you use the project and want to help out please continue! there plenty of small issues to be fixed in the issues page :)

**Comment by davidsunsbk** [comment]
Sure, overall it's a great project and it still has a long way to go compared to traditional Materialize framework. Hope it gets better and I'll see what I can do to help with my limited skills. :)

**Comment by alextrastero** [comment]
we can all learn together! :)

**Pull request merged**
