### PR TITLE
Init modals which have no trigger

### PR DESCRIPTION
**Pull request by cedretaber**
Hi, the modals of the sample page were not work, because which have not be initialized.

### CODE REVIEW

**Comment by alextrastero** [comment]
Just as a note, we need to initialise modals that contain a trigger and also when they don't contain a trigger

**Comment by cedretaber** [comment]
I've clicked buttons but the modals of the examples didn't open. So, I considered that there were broken.

https://react-materialize.github.io/#/modals

It seems that the modals are never initialised which don't contain a trigger.

**Comment by cedretaber** [comment]
Sorry, I have got a mistake.
It might not work only if it's on a sample page (because of react-live?)

**Comment by alextrastero** [comment]
Yes! Once you change the code in react-live it doesn't get re-mounted so the initialise is not called. I'm not sure if we could maybe reinitialise on willReceiveProps ??

**Pull request closed without merging**
