### PR TITLE
Turn button into link if href is present

### PR DESCRIPTION
**Pull request by ruediste**
I am using Buttons as links. This can already be accompished by writing
`<Button floating large className='red' waves='light' icon='add' node="a" href="../account/_add"/>`
This patch alllows to omit the node property.

### CODE REVIEW

**Comment by alextrastero** [comment]
Hey @ruediste, I'm not sure about this PR, I would rather not add more logic to the button if we can help it

**Comment by ruediste** [comment]
Hello @alextrastero. I think rendering buttons as links is important to allow opening the target page in a new tab. To reduce logic in the Button, perhaps pulling out the FAB would be an idea? Could be moved to <Button.FAB ... />. Talking of, what do you thing about a <Button.Link ... />?

**Comment by isaiah** [comment]
@ruediste I can see the usage of it, probably keep the `node` prop when specified?

**Comment by ruediste** [comment]
Good point, just added. I also wrote a test

**Comment by alextrastero** [comment]
I still think this is adding way to much logic to `<Button>` just to avoid adding 1 prop

**Comment by ruediste** [comment]
Thanks for the quick review of the pull request. I'll probably include the logic in a custom wrapper. I added a sample to the documentation instead.

**Comment by isaiah** [comment]
@ruediste :+1:

**Pull request merged**
