### PR TITLE
Caption component not exported

### PR DESCRIPTION
**Pull request by CloudPower97**
# Description

`Caption` component introduced in #701 was not exported

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Nothing to test here.

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by CloudPower97** [comment]
Hey @alextrastero, not sure what's going on with `snyk` here, could you take a look at it whenever possible? :smile:

**Comment by alextrastero** [comment]
Hey @CloudPower97, yikes, good catch. I'm wondering if this component works, could you add a story for it?

**Comment by alextrastero** [comment]
Dunno what's happening with `snyk` will need to see after a new commit

**Comment by CloudPower97** [comment]
Hey @alextrastero , it seems that the problem with `snyk` is gone. Better this way :smiley:

**Pull request merged**
