### PR TITLE
Added the possibility to center the brand logo in the navbar

### PR DESCRIPTION
**Pull request by CloudPower97**
# Description

There is now the possibility to center the brand logo in the navbar.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

I've tested this component in a project I'm currently involved into and it seems to work without any problems.

# Checklist:

- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by CloudPower97** [comment]
@alextrastero Well, `left` and `right` control the links position.
Writing 
```
<Navbar brand="Educabile" left center className="blue darken-3">
   ...
</Navbar>
```
can be misleading, while writing

```
<Navbar brand="Educabile" left centerLogo className="blue darken-3">
   ...
</Navbar>
```

is not.

Don't you agree with me?

**Comment by alextrastero** [comment]
Ah, good point! I'll need to fire this up locally to check but yes seems right :)

**Comment by alextrastero** [comment]
Would you mind adding some comments to the `propTypes` like other components do? That way when creating the docs it will add it. Specifically for `centerLogo` and `left` `right`

**Comment by CloudPower97** [comment]
@alextrastero Sure, I'm going to do it ASAP.

**Comment by alextrastero** [comment]
ping :)

**Comment by CloudPower97** [comment]
@alextrastero Done ;)

**Comment by alextrastero** [comment]
After having a thought on this, don't you think that the interface should be `left` `right` and `center`? And this props would set the position of the logo it self, and the links would live on the other side of the logo... you follow?

**Comment by joelquek** [comment]
centerLogo did not worked. I think it's missing from the current version?

**Comment by CloudPower97** [comment]
@joelquek Yes, it is. @alextrastero what should I do? I'm ready to make this PR mergable

**Pull request merged**
