### PR TITLE
Adds Divider, Section and Container components

### PR DESCRIPTION
**Pull request by alextrastero**

### CODE REVIEW

**Comment by alextrastero** [comment]
Very true, thanks

**Comment by isaiah** [comment]
@alextrastero Correct me if I'm wrong, isn't there a `export Component from '../file'` syntax that we can use, so we don't have to duplicate the name twice?

**Comment by alextrastero** [comment]
Yup, that's valid

**Comment by alextrastero** [comment]
@isaiah I like the way material-ui only exports one file by moving each component into a separate folder/index.js. That way you could import components individually WDYT?

**Comment by isaiah** [comment]
That's hard to use IMO, people can still import individually by `import
react-materialize/lib/Col`, if they prefer. MaterialUI did that probably
because each component is relatively more complex than ours.

Alexander Odell <notifications@github.com> schrieb am Di., 23. Mai 2017,
09:02:

**Pull request merged**
