### PR TITLE
3.0.0 beta.0 button

### PR DESCRIPTION
**Pull request by onluiz**
# Description
It closes react-materialize/react-materialize#583 (I hope :smile: )

This PR updates `Button` component to work with materializecss 1.0.0-rc.2. It includes:

- New class `.btn-small`
- Now if your element has a class like `.btn-large` or` .btn-small` you no longer need the `.btn` class
- A update of `Button` component docs (used materializecss new Button docs page as example)
- A page for documenting Floating Action Button component (used materializecss new Button docs page as example)
- A helper file called `string-helper`. It is used to captalize and add spaces to titles (for the navbar and header of the page). It was necessary since the Floating Action Component docs page had its title rendered as "FloatingActionPage" (in the header of the page and in the navbar)
- A fix for Floating Action Button. Now it is initialized when `fab` prop is passed
- A test for new class `.btn-small`

There is some items I would like the opinion from the others contributors:

- I have used materializecss docs as base for those changes in our docs. Was it ok?
- What you think about my solution for nav items with more than one word (Floating Action Button)? Any sugestion of how it could be better?
- The fix for Floating Action Button was valid? Is it ok to initialize the component the way I have done?
- There is any other unit tests you guys want me to add?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- Manual tests using the docs
- Unit tests

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

### CODE REVIEW

**Comment by petergarnaes** [comment]
Nice work, however you should PR into the `react-materialize:3.0.0-beta.0` branch, and not `react-materialize:master`.

**Comment by onluiz** [comment]
@petergarnaes thanks. Done!

**Comment by petergarnaes** [comment]
Why are all those irrelevant commits still included :thinking: Would be nice if the PR was just from 
commit: 0d6178d and forward.

**Comment by onluiz** [comment]
@petergarnaes you're right. I'll try to fix it later ou create a new PR. Thanks!

**Comment by onluiz** [comment]
@petergarnaes I reverted that commit.

**Pull request closed without merging**
