### PR TITLE
Collapsible state fix

### PR DESCRIPTION
**Pull request by reesmanp**
issue #80

### CODE REVIEW

**Comment by isaiah** [comment]
@reesmanp Could you rebase to master please?

**Comment by isaiah** [comment]
@reesmanp There is a related spec failing, could you please take a look?

**Comment by reesmanp** [comment]
@isaiah It seems the reason it is failing is because the test is looking for a state to confirm the ability to expand the item. Since I removed the state from this item, it would probably be best to rewrite the test script for this component and have the state be used for Collapsible not CollapsibleItem.

**Comment by alextrastero** [comment]
Nice

**Comment by isaiah** [comment]
@reesmanp Paul, thanks for your input, would you like to become a collaborator?

**Comment by reesmanp** [comment]
@isaiah I would like that very much.

**Comment by alextrastero** [comment]
@reesmanp @isaiah 🎉 cool!!

**Comment by isaiah** [comment]
@reesmanp invite is out

**Pull request merged**
