### PR TITLE
add prepare hook to package.json to make it installable over git

### PR DESCRIPTION
**Pull request by gen-failure**
# Description

By adding the _npm build_ to _prepare_ hook in package.json, this branch can be installed directly using npm like

```bash
npm install git://github.com:react-materialize/react-materialize.git
```
## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

package was installed using npm (more in pr description) and lib/ file was successfully installed by npm

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have not generated a new package version. (the maintainers will handle that)

I didn't consider the comment to be necessary in this case.

### CODE REVIEW

**Comment by alextrastero** [comment]
Hey @gen-failure, thanks for this, could we remove the unrelated commits?

**Comment by gen-failure** [comment]
Removed, I am sorry ;)

**Comment by gen-failure** [comment]
Of course. I added to beta branch because that was the one I wanted to
test, but I suppose I should have do it for master.

po 15. 10. 2018 v 11:04 odesílatel Alexander Odell <notifications@github.com>
napsal:

**Comment by alextrastero** [comment]
cant change base, please cherry pick on master and reopen :)

**Pull request closed without merging**
